name: Doxygen

on:
  push:
    branches:
      - automated-builds
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y doxygen graphviz

      - name: Run Doxygen
        run: doxygen

      - name: Upload Doxygen pages
        uses: actions/upload-artifact@v7
        with:
          name: doxygen-documentation
          path: docs/doxygen/html
